# Generated by Django 3.0.3 on 2020-05-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('fever', models.CharField(max_length=13)),
                ('cough', models.CharField(max_length=13)),
                ('throat', models.TextField(max_length=13)),
                ('breathing', models.TextField(max_length=13)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
