# Generated by Django 3.0.3 on 2020-05-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_users_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserData',
        ),
    ]
