# Generated by Django 3.0.3 on 2020-05-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20200518_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='breathing',
            field=models.IntegerField(max_length=13),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='cough',
            field=models.IntegerField(max_length=13),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='fever',
            field=models.IntegerField(max_length=13),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='throat',
            field=models.IntegerField(max_length=13),
        ),
    ]
