# Generated by Django 3.0.3 on 2020-05-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20200518_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='breathing',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='cough',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='fever',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='result',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='throat',
            field=models.IntegerField(),
        ),
    ]
