# Generated by Django 3.0.3 on 2020-05-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20200518_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
