# Generated by Django 3.0.3 on 2020-05-21 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_auto_20200521_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largedata',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
