# Generated by Django 3.0.3 on 2020-05-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_auto_20200521_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largedata',
            name='result',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='result',
            field=models.IntegerField(),
        ),
    ]
